set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports {clk}]

# vga pins
set_property PACKAGE_PIN P19 [get_ports {h_sync_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {h_sync_o}]
set_property PACKAGE_PIN R19 [get_ports {v_sync_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {v_sync_o}]
set_property PACKAGE_PIN G19 [get_ports {vga_r_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_o[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_o[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_o[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_o[3]}]
set_property PACKAGE_PIN J17 [get_ports {vga_g_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_o[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_o[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_o[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_o[3]}]
set_property PACKAGE_PIN N18 [get_ports {vga_b_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_o[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_o[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_o[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_o[3]}]
